from docx import Document
import os

output_dir = "documents/docx"
os.makedirs(output_dir, exist_ok=True)

# Generate 30 sample DOCX files
for i in range(1, 31):
    doc = Document()
    # Title
    doc.add_heading(f"Meeting Notes #{i}", level=1)
    # Introduction
    doc.add_paragraph(
        "These are autogenerated meeting notes. They simulate a corporate or academic document."
    )
    # Agenda
    doc.add_heading("Agenda", level=2)
    doc.add_paragraph("1. Project updates")
    doc.add_paragraph("2. Budget discussion")
    doc.add_paragraph("3. Next steps")
    # Notes section
    doc.add_heading("Notes", level=2)
    doc.add_paragraph(
        f"The meeting number {i} covered progress on tasks. "
        "Several action points were discussed and assigned to the team."
    )
    # Action items
    doc.add_heading("Action Items", level=2)
    doc.add_paragraph("• Prepare next report draft")
    doc.add_paragraph("• Collect feedback from stakeholders")
    doc.add_paragraph("• Schedule follow-up meeting")

    file_path = os.path.join(output_dir, f"notes_{i}.docx")
    doc.save(file_path)

print("30 DOCX files generated in documents/docx/")
